feat: add logger in config methods
indykite/indykite-sdk-python pull request #123
Opened 2023-02-08 15:05 UTC by cowan-macady

added logger in config methods
methods ignored in coverage are methods only used in examples not in sdk itself

2023-02-09 09:35 UTC, Septimus4 requested changes
Now that we have a proper system for logging and returning error can you update all __init_.py to use them and avoid:
```
    def __init__(self, local=False):
        cred = os.getenv('INDYKITE_APPLICATION_CREDENTIALS')

        # Load the config from File (secondary)
        if (cred is False) or (cred is None):
            cred = os.getenv('INDYKITE_APPLICATION_CREDENTIALS_FILE')
            try:
                if (cred is False) or (cred is None):
                    raise Exception("Missing INDYKITE_APPLICATION_CREDENTIALS or "
                                    "INDYKITE_APPLICATION_CREDENTIALS_FILE environment variable")
            except Exception as exception:
                print(exception)
                return None
```

```
if not cred:
    print("Missing INDYKITE_APPLICATION_CREDENTIALS or INDYKITE_APPLICATION_CREDENTIALS_FILE environment variable")
    return None
```

2023-02-10 09:41 UTC, Septimus4 requested changes

2023-02-10 09:41 UTC, Septimus4 commented on indykite_sdk/model/is_authorized.py
> +            is_authorized_response = IsAuthorizedResponse(decision_time=None, decisions={})
Are we sure we want to return` IsAuthorizedResponse(decision_time=None, decisions={})`, if I understand correctly we get in the `else` only if the response from the Indykite platform does not match the expected proto message, we should maybe raise an error saying we did not understand the response ?

2023-02-10 10:59 UTC, cowan-macady commented on indykite_sdk/model/is_authorized.py
> +            is_authorized_response = IsAuthorizedResponse(decision_time=None, decisions={})
removed

2023-02-10 11:05 UTC, Septimus4 approved these changes

2023-02-10 11:10 UTC, merged