feat: add who authorized
indykite/indykite-sdk-python pull request #150
Opened 2023-04-20 09:09 UTC by cowan-macady

- add who_authorized
- replace get with read in service account methods names
- add etag to service account credentials

2023-04-21 18:31 UTC, Septimus4 requested changes

2023-04-21 18:31 UTC, Septimus4 commented on indykite_sdk/model/authorization_policy_config.py
> +                        status.name
I preferred how it was before. Just handle the case where message_config.status in not in the enum so it does not crash

2023-04-24 06:05 UTC, cowan-macady commented on indykite_sdk/model/authorization_policy_config.py
> +                        status.name
changed! (I could not keep what was before because the value returned by the BE was different)

2023-04-24 06:39 UTC, Septimus4 approved these changes

2023-04-24 07:01 UTC, merged