feat: add identity knowledge methods
indykite/indykite-sdk-python pull request #205
Opened 2023-09-29 18:36 UTC by cowan-macady

Closing ENG-1850

2023-10-02 11:25 UTC, maaland requested changes
Make sure you also add `deprecated` wording to the `get_digital_twin()`, `get_digital_twin_by_token()` and `get_digital_twin_by_property()` in the Identity package. As was done in the [Go implementation](https://github.com/indykite/indykite-sdk-go/pull/143/files#diff-c5abb4600a8ce207aba086c29a2fbb15b21057f66fb872be4bdd7c9f35e695a5)

2023-10-08 19:15 UTC, maaland approved these changes
Looks fine to me, to the extent I can review Python SDK stuff 😅

2023-10-08 19:15 UTC, maaland commented on indykite_sdk/knowledge/identity_knowledge.py
> +    :return: record_error
i don't thin we should call this a *record*_error

2023-10-09 08:05 UTC, cowan-macady commented on indykite_sdk/knowledge/identity_knowledge.py
> +    :return: record_error
sorry, not the response ndeed

2023-10-09 08:26 UTC, cowan-macady commented on indykite_sdk/knowledge/identity_knowledge.py
> +        if not identity_knowledge_response or len(identity_knowledge_response.paths) == 0:
In this case, it is to have the same behavior as in go sdk.
Usually, not response means empty response and the value of the response is "None".
In fact a specific handle of the not response is not really necessary. May be I should change that.
If you have some examples about a None which could be an error, please tell me.
Every error is logged, even the uncaught ones with sys.excepthook = logger.handle_excepthook.
May be I should make a complete check of all methods returns in the sdk to see if something is missing.

2023-10-09 13:05 UTC, Septimus4 commented on indykite_sdk/knowledge/identity_knowledge.py
> +        if not identity_knowledge_response or len(identity_knowledge_response.paths) == 0:
No it seems okay with me, just wanted to make sure

2023-10-09 14:45 UTC, Septimus4 approved these changes

2023-10-09 15:06 UTC, maaland approved these changes

2023-10-09 15:41 UTC, merged