feat: update readme
indykite/indykite-sdk-python pull request #245
Opened 2024-03-15 16:45 UTC by cowan-macady

implementing ENG-2648

2024-03-18 14:02 UTC, kilimandzsaro requested changes
@cowan-macady We are trying to get rid of the "DigitalTwin" concept and the Ingest and Knowledge packages are not using them anymore. I suggest to remove all "DigitalTwin" reference from both name and comments from everywhere. I suggest to use the "IdentityNode" instead of that (if the node is an identity node) or just the "Node" if it's not an identity one.

2024-03-18 14:02 UTC, kilimandzsaro commented on indykite_sdk/usage/knowledge.py
> +"""
I suggest to remove all the "DigitalTwin" reference from here as well.

2024-03-18 15:15 UTC, cowan-macady commented on indykite_sdk/usage/authorization.py
> +    is_authorized_property_parser.add_argument("property_value", help="Digital Twin Identity Property value")
I removed what it is possible so far

2024-03-18 15:15 UTC, cowan-macady commented on indykite_sdk/usage/authorization.py
> +    what_authorized_property_parser.add_argument("property_type", help="Digital Twin Identity Property")
I removed what it is possible so far

2024-03-18 15:15 UTC, cowan-macady commented on indykite_sdk/usage/authorization.py
> +    what_authorized_property_parser.add_argument("property_value", help="Digital Twin Identity Property value")
I removed what it is possible so far

2024-03-18 15:15 UTC, cowan-macady commented on indykite_sdk/usage/ingest.py
> +        ingest_record_digital_twin = client_ingest.ingest_record(record)
I removed what it is possible so far

2024-03-18 15:15 UTC, cowan-macady commented on indykite_sdk/usage/knowledge.py
> +"""
I removed what it is possible so far

2024-03-20 09:02 UTC, kilimandzsaro approved these changes

2024-03-20 09:04 UTC, merged