feat: add entitymatching and delete tags
indykite/indykite-sdk-python pull request #286
Opened 2024-10-15 12:59 UTC by cowan-macady

implement ENG-4427

- add entitymatching
- add deletenodetags
- deprecate IngestRecord

2024-10-16 11:25 UTC, Septimus4 requested changes

2024-10-16 13:22 UTC, cowan-macady commented on indykite_sdk/ingest/ingest_record.py
> +@deprecated
it did not work in utils. I will add the warning in the function

2024-10-16 18:19 UTC, cowan-macady commented on indykite_sdk/ingest/ingest_record.py
> +@deprecated
updated

2024-10-16 18:19 UTC, cowan-macady commented on tests/test_ingest_batch.py
added

2024-10-16 18:20 UTC, cowan-macady commented on indykite_sdk/model/entity_matching_pipeline_config.py
> +        self.report_type = report_type
changed for this one

2024-10-18 10:49 UTC, Septimus4 approved these changes
Great, it looks a lot better, and it will be a lot easier to maintain. Hoping we slowly refactor the rest, and make sure next PRs enforce the same rules

2024-10-18 10:52 UTC, cowan-macady commented
I added some more refactoring. Will continue next pr

2024-10-18 11:02 UTC, merged